-- MySQL Script generated by MySQL Workbench
-- pon, 30 lip 2018, 22:27:43
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`employee`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`employee` (
  `id` INT NOT NULL,
  `name` VARCHAR(45) NULL,
  `lastname` VARCHAR(45) NULL,
  `note` TEXT NULL,
  `working_hour_cost` FLOAT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`order`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`order` (
  `id` INT NOT NULL,
  `acceptance_date` DATE NULL,
  `estimate_start_date` DATE NULL,
  `start_work_date` DATE NULL,
  `problem_details` TEXT NULL,
  `repair_details` TEXT NULL,
  `status` TEXT NULL,
  `total_cost_for_customer` FLOAT NULL,
  `total_cost_of_the_parts_used` FLOAT NULL,
  `work_hours_count` INT NULL,
  `employee_id` INT NOT NULL,
  PRIMARY KEY (`id`, `employee_id`),
  INDEX `fk_order_employee1_idx` (`employee_id` ASC),
  CONSTRAINT `fk_order_employee1`
    FOREIGN KEY (`employee_id`)
    REFERENCES `mydb`.`employee` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`customer`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`customer` (
  `id` INT NOT NULL,
  `name` VARCHAR(45) NULL,
  `lastname` VARCHAR(45) NULL,
  `date_of_birth` DATE NULL,
  `order_id` INT NOT NULL,
  PRIMARY KEY (`id`, `order_id`),
  INDEX `fk_customer_order1_idx` (`order_id` ASC),
  CONSTRAINT `fk_customer_order1`
    FOREIGN KEY (`order_id`)
    REFERENCES `mydb`.`order` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`car`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`car` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `model` VARCHAR(45) NULL,
  `brand` VARCHAR(45) NULL,
  `date_of_production` DATE NULL,
  `registration_number` VARCHAR(45) NULL,
  `next_technical_inspection_date` DATE NULL,
  `order_id` INT NOT NULL,
  `customer_id` INT NOT NULL,
  `customer_order_id` INT NOT NULL,
  PRIMARY KEY (`id`, `order_id`, `customer_id`, `customer_order_id`),
  INDEX `fk_car_order1_idx` (`order_id` ASC),
  INDEX `fk_car_customer1_idx` (`customer_id` ASC, `customer_order_id` ASC),
  CONSTRAINT `fk_car_order1`
    FOREIGN KEY (`order_id`)
    REFERENCES `mydb`.`order` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_car_customer1`
    FOREIGN KEY (`customer_id` , `customer_order_id`)
    REFERENCES `mydb`.`customer` (`id` , `order_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
